# Generated by Django 2.0 on 2018-05-25 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('close', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(editable=False)),
                ('price', models.FloatField(editable=False, null=True)),
                ('uuid', models.CharField(editable=False, max_length=45, null=True, validators=[django.core.validators.MinLengthValidator(35)])),
                ('side', models.CharField(editable=False, max_length=4, validators=[django.core.validators.MinLengthValidator(1)])),
                ('state', models.CharField(editable=False, max_length=20)),
                ('date', models.DateField(editable=False, null=True)),
                ('stock', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='portfolio.StockModel')),
            ],
            options={
                'ordering': ['stock'],
            },
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='stocks',
            field=models.ManyToManyField(to='portfolio.StockModel'),
        ),
    ]
