# Generated by Django 2.0 on 2018-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='created_at',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trademodel',
            name='updated_at',
            field=models.DateField(editable=False, null=True),
        ),
    ]
