# Generated by Django 2.0 on 2018-06-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180612_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='close',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='ticker',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
