# Generated by Django 2.0 on 2018-06-12 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180612_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='stock',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.StockModel'),
        ),
    ]
